### PR TITLE
Scaffolding Complete

### PR DESCRIPTION
**Pull request by garciaraulin**
Project structure, scaffolding, .gitignore complete

### CODE REVIEW

**Comment by unoriginal1234** [comment]
Looks great, looking forward to testing the gitignore

**Comment by RichieLi1745** [comment]
Nice pull bro! 😮‍💨 👍

**Review by Battletortoise — APPROVED** [review]
What can i say, wow. amazing work out there

**Comment by garciaraulin** [comment]
Let's get this done! 😬

**Pull request merged**
